create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  team_name text not null,
  team_code text not null unique,
  current_stage integer not null default 1,
  completed_count integer not null default 0,
  hint_count integer not null default 0,
  is_finished boolean not null default false,
  started_at timestamptz,
  finished_at timestamptz
);

alter table public.teams enable row level security;

drop policy if exists "teams_select_public" on public.teams;
drop policy if exists "teams_insert_public" on public.teams;
drop policy if exists "teams_update_public" on public.teams;

create policy "teams_select_public"
on public.teams
for select
to anon
using (
  team_code in ('TEAM01', 'TEAM02', 'TEAM03', 'TEAM04', 'TEAM05')
);

create policy "teams_insert_public"
on public.teams
for insert
to anon
with check (
  team_code in ('TEAM01', 'TEAM02', 'TEAM03', 'TEAM04', 'TEAM05')
);

create policy "teams_update_public"
on public.teams
for update
to anon
using (
  team_code in ('TEAM01', 'TEAM02', 'TEAM03', 'TEAM04', 'TEAM05')
)
with check (
  team_code in ('TEAM01', 'TEAM02', 'TEAM03', 'TEAM04', 'TEAM05')
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'teams'
  ) then
    alter publication supabase_realtime add table public.teams;
  end if;
end $$;

insert into public.teams (
  team_name,
  team_code,
  current_stage,
  completed_count,
  hint_count,
  is_finished,
  started_at,
  finished_at
)
values
  ('1조', 'TEAM01', 1, 0, 0, false, null, null),
  ('2조', 'TEAM02', 1, 0, 0, false, null, null),
  ('3조', 'TEAM03', 1, 0, 0, false, null, null),
  ('4조', 'TEAM04', 1, 0, 0, false, null, null),
  ('5조', 'TEAM05', 1, 0, 0, false, null, null)
on conflict (team_code) do update
set
  team_name = excluded.team_name;
